### ISSUE TITLE
Problems with Release 1.0.2

### ISSUE THREAD

**Issue by rkilchmn** [saygoweb/frontaccounting-module-sgw_import#7]
Thanks for producing the release 1.0.2.

I noticed 3 problems which may be due to my installation ( I am running on PHP 8.1.13)

1) The release needs to be unpacked into directory modules/sgw_import  (based on the filename, I was assuming "frontaccounting-module-sgw_import") because otherwise the hook class cannot be found because it depends on the sub-folder name "sgw_import". That's probably just something that would be helpful to know in the readme file.

2) When executing "Configure Import Transactions" (sgw_import/admin/admin_file_type.php) I get the following error: 
`Unhandled exception [0]: AdminFileTypeView::view(): Argument #1 ($fileTypeModel) must be of type SGW_Import\Model\ImportFileTypeModel, bool given, called in modules/sgw_import/includes/Controller/AdminFileType.php on line 49. in file: modules/sgw_import/admin/admin_file_type.php at line 38`

3) When executing "Import Transactions" (sgw_import/import_files.php)  I get the following error: 
`Unhandled exception [0]: Anorm: Could not parse PDOException. in file: modules/sgw_import/vendor/saygoweb/anorm/src/TableMaker.php at line 68`

If you could point me to resolution of 2) and 3) I would be verry grateful.

**Comment by cambell-prince** [comment]
Well, this is a very delayed response.

1. Yes, you're right. It needs to be unpacked into `modules/sgw_import`. I've now improved the README.
2. Yes, that's because there's no import definition.  You need to upload a csv against a bank first, before configuring it.  I've now improved the README, and added better error handling.
3. That would suggest that a) the database didn't get upgraded see `data/0.1.0.sql`, and b) that we didn't like the exception thrown.  That can depend on the database version. I'm using MariaDB 10.4 which works for me.
